# Generated by Django 5.1.4 on 2026-06-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('troupe', models.CharField(blank=True, default='', max_length=128)),
                ('genre', models.CharField(choices=[('concert', '演唱会'), ('drama', '话剧'), ('musical', '音乐剧'), ('opera', '戏曲'), ('other', '其他')], default='concert', max_length=16)),
                ('status', models.CharField(choices=[('on_sale', '售票中'), ('upcoming', '待开票'), ('ended', '已结束')], default='upcoming', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shows',
            },
        ),
        migrations.CreateModel(
            name='RefundRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('tiers', models.JSONField(default=list, help_text='阶梯规则列表，每项包含 hours_before(开演前小时数) 和 fee_rate(手续费率0-1)，按 hours_before 降序排列')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_rule', to='tickets.show')),
            ],
            options={
                'db_table': 'refund_rules',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.CharField(default='', max_length=64)),
                ('start_at', models.DateTimeField()),
                ('total_seats', models.IntegerField(default=0)),
                ('sold_seats', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='tickets.show')),
            ],
            options={
                'db_table': 'performances',
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('paid', '已支付'), ('cancelled', '已取消'), ('refunded', '已退票'), ('partially_refunded', '部分退票'), ('exchanged', '已改签')], default='paid', max_length=32)),
                ('exchange_count', models.IntegerField(default=0)),
                ('has_exchanged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_children', to='tickets.ticketorder')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tickets.performance')),
            ],
            options={
                'db_table': 'ticket_orders',
            },
        ),
        migrations.CreateModel(
            name='RefundExchangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('refund_apply', '申请退票'), ('refund_process', '处理退款'), ('exchange', '改签')], max_length=32)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='涉及金额：退票退款额/改签差价', max_digits=12)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('operator', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tickets.performance')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tickets.ticketorder')),
            ],
            options={
                'db_table': 'refund_exchange_logs',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('original_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hours_before_show', models.IntegerField(default=0, help_text='申请退票时距开演的小时数')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('refunded', '已退款'), ('rejected', '已拒绝')], default='pending', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=256)),
                ('operator', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='tickets.performance')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='tickets.ticketorder')),
            ],
            options={
                'db_table': 'refunds',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('from_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('to_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_diff', models.DecimalField(decimal_places=2, default=0, help_text='正数需补款，负数需退款', max_digits=12)),
                ('diff_settled', models.BooleanField(default=False)),
                ('operator', models.CharField(blank=True, default='', max_length=64)),
                ('remark', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_from', to='tickets.performance')),
                ('to_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_to', to='tickets.performance')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='tickets.ticketorder')),
            ],
            options={
                'db_table': 'exchanges',
            },
        ),
    ]
